from dataclasses import dataclass
from typing import Protocol
from PIL import Image
@dataclass
class VLMResult: text: str; input_tokens: int=0; output_tokens: int=0; latency_ms: float=0.0
@dataclass
class MemoryStats: allocated_mb: float=0.0; reserved_mb: float=0.0; max_allocated_mb: float=0.0
class BaseVLM(Protocol):
    def load(self)->None: ...
    def warmup(self)->None: ...
    def generate(self,image:Image.Image,prompt:str,max_new_tokens:int=512)->VLMResult: ...
    def get_memory_stats(self)->MemoryStats: ...
    def unload(self)->None: ...
